steps:
  # Step 1: Trigger preprocess-stock-data service
  - name: 'curlimages/curl'
    args:
      - '-X'
      - 'POST'
      - '-H'
      - 'Authorization: Bearer $(gcloud auth print-identity-token)'
      - '-H'
      - 'Content-Type: application/json'
      - '-d'
      - '{"trigger": "true"}'
      - 'https://preprocess-stock-data-184982369838.us-east1.run.app'

  # Step 2: Trigger preprocessed-news-articles service
  - name: 'curlimages/curl'
    args:
      - '-X'
      - 'POST'
      - '-H'
      - 'Authorization: Bearer $(gcloud auth print-identity-token)'
      - '-H'
      - 'Content-Type: application/json'
      - '-d'
      - '{"trigger": "true"}'
      - 'https://preprocessed-news-articles-184982369838.us-east1.run.app'

  # Step 3: Trigger rag-app service
  - name: 'curlimages/curl'
    args:
      - '-X'
      - 'POST'
      - '-H'
      - 'Authorization: Bearer $(gcloud auth print-identity-token)'
      - '-H'
      - 'Content-Type: application/json'
      - '-d'
      - '{"trigger": "true"}'
      - 'https://rag-app-184982369838.us-east1.run.app'

  # Step 4: Trigger stock-prices-transformed service
  - name: 'curlimages/curl'
    args:
      - '-X'
      - 'POST'
      - '-H'
      - 'Authorization: Bearer $(gcloud auth print-identity-token)'
      - '-H'
      - 'Content-Type: application/json'
      - '-d'
      - '{"trigger": "true"}'
      - 'https://stock-prices-transformed-184982369838.us-east1.run.app'

  # Step 5: Trigger news-articles-preprocessing service
  - name: 'curlimages/curl'
    args:
      - '-X'
      - 'POST'
      - '-H'
      - 'Authorization: Bearer $(gcloud auth print-identity-token)'
      - '-H'
      - 'Content-Type: application/json'
      - '-d'
      - '{"trigger": "true"}'
      - 'https://news-articles-preprocessing-184982369838.us-east1.run.app'

  # Step 6: Trigger news-article-ingestion service
  - name: 'curlimages/curl'
    args:
      - '-X'
      - 'POST'
      - '-H'
      - 'Authorization: Bearer $(gcloud auth print-identity-token)'
      - '-H'
      - 'Content-Type: application/json'
      - '-d'
      - '{"trigger": "true"}'
      - 'https://news-article-ingestion-184982369838.us-east1.run.app'

  # Step 7: Trigger flask-application service
  - name: 'curlimages/curl'
    args:
      - '-X'
      - 'POST'
      - '-H'
      - 'Authorization: Bearer $(gcloud auth print-identity-token)'
      - '-H'
      - 'Content-Type: application/json'
      - '-d'
      - '{"trigger": "true"}'
      - 'https://flask-application-184982369838.us-east1.run.app'

  # Step 8: Trigger flask-app service
  - name: 'curlimages/curl'
    args:
      - '-X'
      - 'POST'
      - '-H'
      - 'Authorization: Bearer $(gcloud auth print-identity-token)'
      - '-H'
      - 'Content-Type: application/json'
      - '-d'
      - '{"trigger": "true"}'
      - 'https://flask-app-184982369838.us-east1.run.app'

  # Step 9: Trigger financial-chatbot service
  - name: 'curlimages/curl'
    args:
      - '-X'
      - 'POST'
      - '-H'
      - 'Authorization: Bearer $(gcloud auth print-identity-token)'
      - '-H'
      - 'Content-Type: application/json'
      - '-d'
      - '{"trigger": "true"}'
      - 'https://financial-chatbot-184982369838.us-west1.run.app'

  # Step 10: Trigger fetch-stock-data service
  - name: 'curlimages/curl'
    args:
      - '-X'
      - 'POST'
      - '-H'
      - 'Authorization: Bearer $(gcloud auth print-identity-token)'
      - '-H'
      - 'Content-Type: application/json'
      - '-d'
      - '{"trigger": "true"}'
      - 'https://fetch-stock-data-184982369838.us-east1.run.app'

  # Step 11: Trigger chatbot-ui service
  - name: 'curlimages/curl'
    args:
      - '-X'
      - 'POST'
      - '-H'
      - 'Authorization: Bearer $(gcloud auth print-identity-token)'
      - '-H'
      - 'Content-Type: application/json'
      - '-d'
      - '{"trigger": "true"}'
      - 'https://chatbot-ui-184982369838.us-east1.run.app'

  # Step 12: Trigger chatbot-container service
  - name: 'curlimages/curl'
    args:
      - '-X'
      - 'POST'
      - '-H'
      - 'Authorization: Bearer $(gcloud auth print-identity-token)'
      - '-H'
      - 'Content-Type: application/json'
      - '-d'
      - '{"trigger": "true"}'
      - 'https://chatbot-container-184982369838.us-west1.run.app'

timeout: "1200s" # Adjust timeout as needed
