name: Build, Push, and Deploy Model Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.CLOUD_RUN_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build Docker Image
      run: docker build -t gcr.io/theta-function-429605-j0/model-pipeline:latest .

    - name: Push Docker Image to Artifact Registry
      run: docker push gcr.io/theta-function-429605-j0/model-pipeline:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy model-pipeline-service \
          --image=gcr.io/theta-function-429605-j0/model-pipeline:latest \
          --region=us-east1 \
          --platform=managed \
          --allow-unauthenticated
