name: Deploy UI

on:
  push:
    branches: [ main ]
    paths:
      - 'ui/**'

env:
  PROJECT_ID: theta-function-429605-j0
  REGION: us-east1
  ARTIFACT_REGISTRY_NAME: ui-server
  SERVICE_NAME: ui-streamlit-app

jobs:
  build-and-deploy-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}
          registry: ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image (UI)
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_NAME }}/${{env.SERVICE_NAME}}:latest -f ui/Dockerfile ui
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_NAME }}/${{env.SERVICE_NAME}}:latest

      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_NAME }}/${{env.SERVICE_NAME}}:latest"
          memory: 1Gi

      - name: Show Output
        run: echo "UI URL: ${{ steps.deploy.outputs.url }}"
